Vagrant.configure("2") do |config|
  config.vm.box = "akachanov/centos8minimal"
# ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 80, host: 8081
  config.vm.provision "docker" do |doc|
    doc.run "nginx", args: "-p 80:80"
  end
end
